set -e
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-hammer /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/corrected/configs/config.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/corrected/corrected.yaml --ext_python_modules_home /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades --max_threads 10 --output_dir /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/corrected --gzip_output
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K21/configs/config.info /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K21/configs/careful_mode.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K33/configs/config.info /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K33/configs/careful_mode.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/spades-core /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/configs/config.info /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/configs/careful_mode.info
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/before_rr.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/before_rr.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/assembly_graph_after_simplification.gfa /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/final_contigs.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/contigs.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/first_pe_contigs.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/first_pe_contigs.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/strain_graph.gfa /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/strain_graph.gfa /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/scaffolds.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/scaffolds.fasta /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/scaffolds.paths /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/scaffolds.paths /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/assembly_graph_with_scaffolds.gfa /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/assembly_graph.fastg /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/assembly_graph.fastg /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/K55/final_contigs.paths /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/contigs.paths
true
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/contigs.fasta --assembled /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/misc/assembled_contigs.fasta --assembly_type contigs --output_dir /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final --bin_home /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/scaffolds.fasta --assembled /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final --bin_home /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin
true
/Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/bin/python3 /Users/weeblesthe2nd/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/scaffolds.fasta --misc_dir /Users/weeblesthe2nd/Desktop/marinum_fastp_final/spades_final/misc --threshold_for_breaking_scaffolds 3
true
